---
# tasks file for install-check_mk-client (Windows only)
- name: Copy agent installation file | WIN_COPY
  win_copy:
    dest: "{{ install_check_mk_client_win_tmp }}"
    src: "{{ install_check_mk_client_win_filename }}"
  tags:
    - install-check-mk-client
- name: Install agent | WIN_PACKAGE
  win_package:
    path: "{{ install_check_mk_client_win_tmp }}"
    creates_path: "{{ install_check_mk_client_win_folder }}"
    state: present
  tags:
    - install-check-mk-client
- name: Generate configuration file from template | WIN_TEMPLATE
  win_template:
    src: "{{ install_check_mk_client_win_config }}"
    dest: "{{ install_check_mk_client_win_folder }}check_mk.ini"
  notify: Restart Windows agent service
  tags:
    - install-check-mk-client
- name: Generate plugins | WIN_TEMPLATE
  win_template:
    src: "{{ item }}.j2"
    dest: "{{ install_check_mk_client_win_folder }}plugins\\{{ item }}"
  with_items: "{{ install_check_mk_client_win_plugins }}"
  notify: Restart Windows agent service
  tags:
    - install-check-mk-client
